### ISSUE TITLE
rhs & tmp?

### ISSUE THREAD

**Issue by marie-bnl** [pikock/pollly#2]
Why does it export and yml of the form 
```yml
rhs:
  tmp:
    key: value
```
?

Why not just 
```yml
key: value
```
?

How are we supposed to use it?
